export const CREATE_DOCTOR = 'CREATE_DOCTOR';
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_DOCTORBYID = 'GET_DOCTORBYID';
export const UPDATE_DOCTOR = 'UPDATE_DOCTOR'
export const DELETE_DOCTOR = 'DELETE_DOCTOR';
export const DOCTORS_ERROR = 'DOCTORS_ERROR';

export const CREATE_PATIENT = 'CREATE_PATIENT';
export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_PATIENTBYID = 'GET_PATIENTBYID';
export const UPDATE_PATIENT = 'UPDATE_PATIENT'
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const PATIENTS_ERROR = 'PATIENTS_ERROR';

export const CREATE_SPECIALIZATION = 'CREATE_SPECIALIZATION';
export const GET_SPECIALIZATIONS = 'GET_SPECIALIZATIONS';
export const GET_SPECIALIZATIONBYID = 'GET_SPECIALIZATIONBYID';
export const UPDATE_SPECIALIZATION = 'UPDATE_SPECIALIZATION'
export const DELETE_SPECIALIZATION = 'DELETE_SPECIALIZATION';
export const SPECIALIZATIONS_ERROR = 'SPECIALIZATIONS_ERROR';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTBYID = 'GET_APPOINTMENTBYID';
export const GET_APPOINTMENTBYDOCTORID = 'GET_APPOINTMENTBYDOCTORID';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const APPOINTMENTS_ERROR = 'APPOINTMENTS_ERROR';

export const LOGIN = 'LOGIN';
export const LOGINS_ERROR = 'LOGINS_ERROR';